AllCops:
  DisabledByDefault: true
  Include:
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'

Style/IndentationWidth:
  Width: 2

Metrics/LineLength:
  Max: 115

Style/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: no_space
  SpaceBeforeBlockParameters: true

Style/TrailingBlankLines:
  EnforcedStyle: final_newline

Style/TrailingWhitespace:
  Enabled: true

Style/SpaceInsideParens:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/MethodCallParentheses:
  Enabled: true

Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: space

Style/SpaceAfterComma:
  Description: 'Use spaces after commas.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#spaces-operators'
  Enabled: true  

Style/SpaceAfterMethodName:
  Enabled: true

Style/SpaceAfterNot:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/ExtraSpacing:
  AllowForAlignment: true

Style/CaseIndentation:
  IndentWhenRelativeTo: case

Style/ClassMethods:
  Enabled: true

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: false

Style/For:
  EnforcedStyle: each

Style/IndentationConsistency:
  EnforcedStyle: normal

Style/InitialIndentation:
  Enabled: true

Style/MultilineIfThen:
  Enabled: true

Style/IfWithSemicolon:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true

Style/OneLineConditional:
  Enabled: true

Style/NestedTernaryOperator:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/NegatedWhile:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: false

Style/RescueModifier:
  Enabled: true

Style/AndOr:
  EnforcedStyle: always

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: true

Style/BeginBlock:
  Enabled: true

Style/BlockComments:
  Enabled: true

Style/BlockEndNewline:
  Enabled: true

Style/MultilineBlockLayout:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/TrailingUnderscoreVariable:
  Enabled: true

Style/CaseEquality:
  Enabled: true

Style/ConstantName:
  Enabled: true

Style/FileName:
  Enabled: true

Style/MethodName:
  EnforcedStyle: snake_case

Style/VariableName:
  EnforcedStyle: snake_case

Style/ClassAndModuleCamelCase:
  Enabled: true

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/ClassVars:
  Enabled: true

Style/VariableInterpolation:
  Enabled: true

Style/AccessModifierIndentation:
  EnforcedStyle: indent

Style/RedundantSelf:
  Enabled: true

Style/WordArray:
  Enabled: true

Style/UnneededCapitalW:
  Enabled: true

Style/SymbolLiteral:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/CommentAnnotation:
  Enabled: true

Style/DeprecatedHashMethods:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/IndentHash:
  EnforcedStyle: special_inside_parentheses

Style/LeadingCommentSpace:
  Enabled: true

Style/AlignHash:
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Style/NumericLiterals:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EndAlignment:
  AlignWith: keyword

Lint/EndInMethod:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Style/StringLiterals:
  Description: 'Checks if uses of quotes match the configured preference.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#consistent-string-literals'
  EnforcedStyle: double_quotes
  Enabled: true
